### ISSUE TITLE
lstat broccoli error

### ISSUE THREAD

**Issue by efx** [adopted-ember-addons/ember-page-title#151]
I test our application using `ember test --launch foo --server --filter SomeTest`. We use ember-mocha.
Recently, I've noticed the following appear in my terminal:
```
Build Error (BroccoliMergeTrees)

[BroccoliMergeTrees: TreeMerger (templates)] error while merging the following:
  1.  [BroccoliMergeTrees: Addon#treeFor (ember-page-title - templates)]
  2.  [object Object]
ENOENT: no such file or directory, lstat
```
Relevant stack trace:
```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: [BroccoliMergeTrees: TreeMerger (templates)] error while merging the following:
  1.  [BroccoliMergeTrees: Addon#treeFor (ember-page-title - templates)]
  2.  [object Object]
ENOENT: no such file or directory, lstat '/tmp/broccoli-8616812ib74Tmyrg/out-002-broccoli_merge_trees_addon_tree_for_ember_page_title_templat'
    at Object.lstatSync (fs.js:845:3)
    at makeFSObjectCleanedUp (/node_modules/fs-updater/index.js:68:18)
    at makeFSObject (/node_modules/fs-updater/index.js:64:10)
    at directoriesWithInputPaths.inputPaths.map.inputPath (/node_modules/ember-cli/node_modules/merge-trees/index.js:37:17)
    at Array.map (<anonymous>)
    at MergeTrees._getMergedDirectory (/node_modules/ember-cli/node_modules/merge-trees/index.js:36:53)
    at MergeTrees.merge (/node_modules/ember-cli/node_modules/merge-trees/index.js:27:20)
    at BroccoliMergeTrees.build (/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:36:21)
    at resolve (/node_modules/broccoli/lib/wrappers/transform-node.js:29:35)
    at new Promise (<anonymous>)
    at TransformNodeWrapper.build (/node_modules/broccoli/lib/wrappers/transform-node.js:21:12)
    at Promise.resolve.then.then.then (/node_modules/broccoli/lib/builder.js:116:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  - code: [undefined]
  - codeFrame: [BroccoliMergeTrees: TreeMerger (templates)] error while merging the following:
  1.  [BroccoliMergeTrees: Addon#treeFor (ember-page-title - templates)]
  2.  [object Object]
ENOENT: no such file or directory, lstat '/tmp/broccoli-8616812ib74Tmyrg/out-002-broccoli_merge_trees_addon_tree_for_ember_page_title_templat'
  - errorMessage: [BroccoliMergeTrees: TreeMerger (templates)] error while merging the following:
  1.  [BroccoliMergeTrees: Addon#treeFor (ember-page-title - templates)]
  2.  [object Object]
ENOENT: no such file or directory, lstat '/tmp/broccoli-8616812ib74Tmyrg/out-002-broccoli_merge_trees_addon_tree_for_ember_page_title_templat'
        at BroccoliMergeTrees (TreeMerger (templates))
-~- created here: -~-
    at BroccoliMergeTrees.Plugin (/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:10:53)
    at mergeTrees (/node_modules/ember-cli/lib/broccoli/merge-trees.js:90:33)
    at EmberApp.getAddonTemplates (/node_modules/ember-cli/lib/broccoli/ember-app.js:1158:27)
    at EmberApp.toArray (/node_modules/ember-cli/lib/broccoli/ember-app.js:1674:12)
    at EmberApp.toTree (/node_modules/ember-cli/lib/broccoli/ember-app.js:1803:36)
    at module.exports (/ember-cli-build.js:90:13)
    at Builder.readBuildFile (/node_modules/ember-cli/lib/models/builder.js:51:14)
    at Builder.setupBroccoliBuilder (/node_modules/ember-cli/lib/models/builder.js:65:22)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: [BroccoliMergeTrees: TreeMerger (templates)] error while merging the following:
  1.  [BroccoliMergeTrees: Addon#treeFor (ember-page-title - templates)]
  2.  [object Object]
ENOENT: no such file or directory, lstat '/tmp/broccoli-8616812ib74Tmyrg/out-002-broccoli_merge_trees_addon_tree_for_ember_page_title_templat'
        at BroccoliMergeTrees (TreeMerger (templates))
-~- created here: -~-
    at BroccoliMergeTrees.Plugin (/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:10:53)
    at mergeTrees (/node_modules/ember-cli/lib/broccoli/merge-trees.js:90:33)
    at EmberApp.getAddonTemplates (/node_modules/ember-cli/lib/broccoli/ember-app.js:1158:27)
    at EmberApp.toArray (/node_modules/ember-cli/lib/broccoli/ember-app.js:1674:12)
    at EmberApp.toTree (/node_modules/ember-cli/lib/broccoli/ember-app.js:1803:36)
    at module.exports (/ember-cli-build.js:90:13)
    at Builder.readBuildFile (/node_modules/ember-cli/lib/models/builder.js:51:14)
    at Builder.setupBroccoliBuilder (/node_modules/ember-cli/lib/models/builder.js:65:22)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: TreeMerger (templates)
  - nodeName: BroccoliMergeTrees
  - originalErrorMessage: [BroccoliMergeTrees: TreeMerger (templates)] error while merging the following:
  1.  [BroccoliMergeTrees: Addon#treeFor (ember-page-title - templates)]
  2.  [object Object]
ENOENT: no such file or directory, lstat '/tmp/broccoli-8616812ib74Tmyrg/out-002-broccoli_merge_trees_addon_tree_for_ember_page_title_templat'
  - stack: Error: [BroccoliMergeTrees: TreeMerger (templates)] error while merging the following:
  1.  [BroccoliMergeTrees: Addon#treeFor (ember-page-title - templates)]
  2.  [object Object]
ENOENT: no such file or directory, lstat '/tmp/broccoli-8616812ib74Tmyrg/out-002-broccoli_merge_trees_addon_tree_for_ember_page_title_templat'
    at Object.lstatSync (fs.js:845:3)
    at makeFSObjectCleanedUp (/node_modules/fs-updater/index.js:68:18)
    at makeFSObject (/node_modules/fs-updater/index.js:64:10)
    at directoriesWithInputPaths.inputPaths.map.inputPath (/node_modules/ember-cli/node_modules/merge-trees/index.js:37:17)
    at Array.map (<anonymous>)
    at MergeTrees._getMergedDirectory (/node_modules/ember-cli/node_modules/merge-trees/index.js:36:53)
    at MergeTrees.merge (/node_modules/ember-cli/node_modules/merge-trees/index.js:27:20)
    at BroccoliMergeTrees.build (/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:36:21)
    at resolve (/node_modules/broccoli/lib/wrappers/transform-node.js:29:35)
    at new Promise (<anonymous>)
    at TransformNodeWrapper.build (/node_modules/broccoli/lib/wrappers/transform-node.js:21:12)
    at Promise.resolve.then.then.then (/node_modules/broccoli/lib/builder.js:116:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I have also noticed the live server connection dies intermittently. It could relate to this error.

# versions
```
ember --version && npm ls ember-page-title
ember-cli: 3.10.1
node: 10.16.0
os: darwin x64
my-project@2.54.0-dev
└── ember-page-title@5.0.2
```

**Comment by knownasilya** [comment]
@efx did you find a solution?

**Comment by efx** [comment]
@knownasilya unfortunately not. I notice this infrequently but it has not been a blocker. And I lack the energy to solve it :)

**Comment by knownasilya** [comment]
Give v6 a try.

**Comment by raido** [comment]
v5.x had https://github.com/adopted-ember-addons/ember-page-title/tree/5.0.2/app/templates - so I assume that was reason for intermediate failures. 

v6 removed `app/templates` folder, so this should be not be relevant anymore.
